name: Latest Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python and create virtual environment
        run: make install

      - name: Install dependencies
        run: make install

      - name: Build package
        run: make build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
